services:
  nginx:
    container_name: mt-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - mt-frontend-dist:/usr/share/nginx/html

  frontend:
    container_name: mt-frontend
    image: hashim6789/task_frontend:latest
    environment:
      - NODE_ENV=production
    volumes:
      - mt-frontend-dist:/app/frontend/dist
    env_file:
      - ./frontend/.env.local

  backend:
    container_name: mt-backend
    image: hashim6789/task_backend:latest
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

volumes:
  mt-frontend-dist:
