export const HttpResponse = {
  SERVER_ERROR: "Internal server error",
  USER_EXIST: "User already exist",
  PAGE_NOT_FOUND: "Route not found",
  USER_NOT_FOUND: "User not found",
  PASSWORD_INCORRECT: "Incorrect password, try again",
  NO_TOKEN: "Token not provided",
  OTP_INCORRECT: "Incorrect otp, try again",
  OTP_NOT_FOUND: "Otp not found",
  INVALID_CREDENTIALS: "Invalid credentials",
  USER_CREATION_FAILED: "User creation failed",
  USER_CREATION_SUCCESS: "User created successfully",
  GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully",
  EMAIL_EXIST: "Email already exist",
  INVALID_EMAIL: "Invalid email address",
  UNEXPECTED_KEY_FOUND: "Unexpected key found",
  RESET_PASS_LINK: "Link for resetting password is sended to email",
  TOKEN_EXPIRED: "Token not valid or expired!",
  PASSWORD_CHANGE_SUCCESS: "Password changed successfully!",
  UNAUTHORIZED: "Unauthorized access!",
  USERNAME_EXIST: "Username Already Exist",
  NO_PAYLOAD: "Payload not found",
  USERNAME_CHANGED: "Username has been changed successfully",
  SAME_USERNAME: "Cannot change to old username",
  LOGOUT_SUCCESS: "User Logout successfully",
  INVALID_ID: "Invalid ID format",
  NO_ACCESS_RESOURCE: "You have no access!",
  INVALID_REFRESH_TOKEN: "Invalid refresh token!",
  INVALID_ACCESS_TOKEN: "Invalid access token!",
  TASK_NOT_FOUND: "The task not found!",
  USER_BLOCKED: "The User blocked!",
  TASK_ALREADY_EXIST: "The task already exist!",
  TASK_ALREADY_ASSIGNED: "The task already assigned!",
  EMAIL_REQUIRED: "The email is required!",
  USERNAME_REQUIRED: "The username is required!",
  ALREADY_ON_STATUS: "Already on that status",
  CANT_CHANGE_STATUS: "Cannot be change to this status!",
  ONLY_MOVE_TODO_TO_INPROGRESS:
    "Task can only move from 'todo' to 'in-progress'",
  ONLY_MOVE_INPROGRESS_COMPLETED:
    "Task can only move from 'in-progress' to 'completed'",
  INVALID_TASK_STATUS: "Invalid task status",
  USER_BLOCKED_OR_NOT_FOUND: "The user blocked or not found!",
  DUE_DATE_NOT_OVER: "The due date of the task is not over!",
};
