name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/task_backend:latest .

      - name: Push backend Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/task_backend:latest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/task_frontend:latest .

      - name: Push frontend Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/task_frontend:latest
